apiVersion: v1
kind: Service
metadata:
  namespace: jenkinstest
  name: movie-db
spec:
  selector:
    app: movie-db
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  namespace: jenkinstest
  name: pwdmovie
type: Opaque
data:
  password: bW92aWVfZGJfcGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapmovie
  namespace: jenkinstest
data:
  username: movie_db_username
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkinstest
  name: movie-db
spec:
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        env:

        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmapmovie
              key: username

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pwdmovie
              key: password
        - name: POSTGRES_DB
          value: "movie_db_dev"
        volumeMounts:
        - name: movie-db-data
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: movie-db-data
        persistentVolumeClaim:
          claimName: movie-db-pvc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkinstest
  name: movie-service
spec:
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
      - name: movie-service
        image: lisandru1208/movie-service:latest 
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--loop", "asyncio"]
        env:
        - name: DATABASE_URI
          value: "postgresql://movie_db_username:movie_db_password@movie-db:5432/movie_db_dev"
        - name: CAST_SERVICE_HOST_URL
          value: "http://movie-service:8000/api/v1/movies/"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkinstest
  name: cast-db
spec:
  selector:
    app: cast-db
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: v1
kind: Secret
metadata:
  namespace: jenkinstest
  name: pwdcast
type: Opaque
data:
  password: Y2FzdF9kYl9wYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapcast
  namespace: jenkinstest
data:
  username: cast_db_username
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkinstest
  name: cast-db
spec:
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
      - name: postgres
        image: postgres:12.1-alpine
        env:

        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pwdcast
              key: password

        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: configmapcast
              key: username

        - name: POSTGRES_DB
          value: "cast_db_dev"

        volumeMounts:
          - name: cast-db-data
            mountPath: /var/lib/postgresql/data/
      volumes:
      - name: cast-db-data
        persistentVolumeClaim:
          claimName: cast-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkinstest  
  name: cast-service
spec:
  selector:
    app: cast-service
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkinstest  
  name: movie-service
spec:
  selector:
    app: movie-service
  ports:
    - protocol: TCP
      port: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkinstest
  name: cast-service
spec:
  selector:
    matchLabels:
      app: cast-service
  template:
    metadata:
      labels:
        app: cast-service
    spec:
      containers:
      - name: cast-service
        image: lisandru1208/cast-service:latest
        command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--loop", "asyncio"]
        env:
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: configmapcast
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pwdcast
                key: password
          - name: DB_HOST
            value: "cast-db"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "cast_db_dev"
          - name: DATABASE_URI
            value: "postgresql://$(DB_USERNAME):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: jenkinstest
data:
  default.conf: |
    server {
      listen 8081;

      location /api/v1/movies {
        proxy_pass http://movie-service:8000/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast-service:8000/api/v1/casts;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  namespace: jenkinstest
  name: nginx-lb
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jenkinstest
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 8081
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: config
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jenkinstest
  name: movie-db-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: jenkinstest
  name: cast-db-pvc
spec:
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 1Gi } }